### ISSUE TITLE
Crash on startup (login required?)

### ISSUE THREAD

**Issue by wolfgang42** [WindmillHelix/Brickficiency2#18]
I cloned Brickficiency and tried to run it in Visual Studio, but it crashes during startup with the following error:
```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=There is an error in XML document (1, 3).
  Source=System.Xml
  StackTrace:
       at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
       at WindmillHelix.Brickficiency2.Common.Xml.TypedXmlSerializer`1.Deserialize(String xml) in C:\Users\wfaust\Documents\Development\Brickficiency2\WindmillHelix.Brickficiency2.Common\Xml\TypedXmlSerializer.cs:line 38
       at WindmillHelix.Brickficiency2.ExternalApi.Bricklink.BricklinkCatalogApi.DownloadCatalog[T](String postString) in C:\Users\wfaust\Documents\Development\Brickficiency2\WindmillHelix.Brickficiency2.ExternalApi\Bricklink\BricklinkCatalogApi.cs:line 78
       at WindmillHelix.Brickficiency2.ExternalApi.Bricklink.BricklinkCatalogApi.DownloadColorList() in C:\Users\wfaust\Documents\Development\Brickficiency2\WindmillHelix.Brickficiency2.ExternalApi\Bricklink\BricklinkCatalogApi.cs:line 20
       at WindmillHelix.Brickficiency2.Services.Data.ColorService.GetItemsFromSource() in C:\Users\wfaust\Documents\Development\Brickficiency2\WindmillHelix.Brickficiency2.Services\Data\ColorService.cs:line 41
       at WindmillHelix.Brickficiency2.Services.Data.CachedDataService`1.Refresh() in C:\Users\wfaust\Documents\Development\Brickficiency2\WindmillHelix.Brickficiency2.Services\Data\CachedDataService.cs:line 43
       at WindmillHelix.Brickficiency2.Services.Data.DataUpdateService.UpdateData() in C:\Users\wfaust\Documents\Development\Brickficiency2\WindmillHelix.Brickficiency2.Services\Data\DataUpdateService.cs:line 86
       at Brickficiency.UI.InitializationForm.DoDataUpdate() in C:\Users\wfaust\Documents\Development\Brickficiency2\Brickficiency\UI\InitializationForm.cs:line 102
       at Brickficiency.UI.InitializationForm.InitializeApplication() in C:\Users\wfaust\Documents\Development\Brickficiency2\Brickficiency\UI\InitializationForm.cs:line 58
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146232000
       LineNumber=1
       LinePosition=3
       Message='doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.
       Source=System.Xml
       SourceUri=""
       StackTrace:
            at System.Xml.XmlTextReaderImpl.Throw(Exception e)
            at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
            at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
            at System.Xml.XmlReader.MoveToContent()
            at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderCatalogContainer1.Read4_CATALOG()
       InnerException: 
```

`xml` appears to contain the HTML for the BrickLink login page. Is there somewhere I need to put the credentials so the program can start?

**Comment by wolfgang42** [comment]
I just tried the 2.0.1a release and that works fine. Maybe the fix never got pushed to GitHub?

**Comment by brakejen** [comment]
Both code from repository and in published zip/gz fails when compiled and run, with the mentioned error. And the binaries provided along with 2.0.1a differ both in numbers and size. So whatever is in that zip with compiled binaries are not built with the code available. I'll try to figure out what's different. But whoever built that binary package would help a lot if uploading the latest source code.

**Comment by wolfgang42** [comment]
I assume that @esampsonite built the package since they're the one that created the release.

**Comment by ghost** [comment]
The bug has been fixed and source code updated. I have not seen any new release yet though.

**Comment by spockinerfurt** [comment]
This error still persists in last `develop` state. I quickly debugged this error:
When trying to download to color XML BrickLink sends the login page instead for not being logged in what results in this error.
The login window is never shown before, however.
